Pizzas
DanielIllanes/PizzaShop pull request #3
Opened 2018-09-13 21:28 UTC by DanielIllanes

2018-09-17 14:06 UTC, raullp requested changes

2018-09-17 14:06 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/IngredientsController.java
> +    @GetMapping("/new/{name}")
@PostMapping()
{
  name: "Fluor"
}

```
{
  name: "Fluor",
  id: 1,
  link: "http://localhost/v1/api/ingridientes/{id}"
}
```

2018-09-17 14:06 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/IngredientsController.java
> +    @GetMapping("/new/{name}")
201 === Http Status CREATED
200 === OK
400 === Bad Requet
404
409

2018-09-17 14:06 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasController.java
> +    public Iterable<Pizza> allPizzas(){
ModelMapper
What is the expected response json example.

2018-09-17 14:06 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasTypesController.java
> +@RequestMapping("/pizzaTypes")
resource naming, no `camelCase`   `snake-case`   "/pizza-types"

2018-09-17 14:09 UTC, DanielIllanes commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasController.java
> +    public Iterable<Pizza> allPizzas(){
The expected response would be:
{
   "pizzatype":"Hawaiian",
   "crust":"FILLED_WITH_CHEESE",
   "cheese":"ROQUEFORT",
   "sauce":"BECHAMEL",
   "toppings":"[Flour, Crushed red pepper]",
   "ingredients":"[Pepperoni, Yeast]"
}

and the actual response is:
{
   "pizzatype":"Hawaiian",
   "crust":"FILLED_WITH_CHEESE",
   "cheese":"ROQUEFORT",
   "sauce":"BECHAMEL",
   "toppings":"[2, 4]",
   "ingredients":"[1, 2]"
}

2018-09-17 21:31 UTC, raullp requested changes

2018-09-17 21:31 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/IngredientsController.java
> +        return new ResponseEntity<>(this.ingredientsRepository.save(newIngredient), HttpStatus.OK);
this should be a 201 HttpStatus.CREATED

2018-09-17 21:31 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasController.java
> +    public Iterable<Pizza> allPizzas(){
Please take a look at the pagination :D 
https://docs.spring.io/spring-data/rest/docs/2.0.0.M1/reference/html/paging-chapter.html

send me the api desing url before you start implementing it.

2018-09-17 21:31 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasController.java
> +    public Iterable<Pizza> allPizzas(){
As I mentioned to you before, please let me know if this might help on what you are trying to do here.
http://modelmapper.org/

Let's discuss the output data before implementing it

2018-09-17 21:31 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasTypesController.java
> +        return this.pizzasTypesRepository.findById(id);
what happens if you sent a request to a non existent end point?

2018-09-18 13:39 UTC, DanielIllanes commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasTypesController.java
> +        return this.pizzasTypesRepository.findById(id);
it redirects to a Whitelabel Error Page. But It can be disabled for handling and displaying the errors in another way.

2018-09-19 15:23 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/IngredientsController.java
> +    public Optional<Ingredient> byId(@PathVariable(value= "id") Long id){
why do you have an optional here?

2018-09-19 15:23 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/IngredientsController.java
> +    public Optional<Ingredient> byId(@PathVariable(value= "id") Long id){
if the object does not exist, you just return a 404 (NOT_FOUND) without content

2018-09-19 15:28 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasController.java
> +        Iterable<Pizza> pizzas =this.pizzasRepository.findAll();
@DanielIllanes, One more thing... I don't really understand what are you doing here. Let's have a quick call to discuss abou it.

2018-09-19 21:59 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasTypesController.java
> +        if(!this.pizzasTypesRepository.findById(id).isPresent()){
exists

2018-09-19 21:59 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/PizzasTypesController.java
> +            return new ResponseEntity(HttpStatus.NOT_FOUND);
ResponseEntity.notFound()

2018-09-19 21:59 UTC, raullp commented on src/main/java/com/pizzashop/pizzashop/Controllers/ToppingsController.java
> +@RequestMapping("/api/v1/toppings")
please use the base path prop

`spring.data.rest.basePath=/api/v1`

`server.contextPath=/api/v1`

2018-09-19 21:59 UTC, raullp commented on src/test/java/com/pizzashop/pizzashop/PizzaTypesTests.java
> +        assertEquals(4, numberOfPizzasTypes);
hamcrest 

`assertThat(toppingList, size(4));`

2018-09-19 21:59 UTC, raullp commented on src/test/java/com/pizzashop/pizzashop/PizzaTypesTests.java
> +        assertEquals(4, numberOfPizzasTypes);
```
Given
  Insert n items with a pattern in the name  "daniel_(uui|timestamp)_\d"
When
  items.each | item| repository.save(item)
Then
  items.each | item| assertNotNull(repository.findByName(item));
```

2018-09-20 18:02 UTC, raullp approved these changes

2018-09-20 18:03 UTC, merged